### ISSUE TITLE
Angular examples

### ISSUE THREAD

**Issue by szymoc** [eclipse-sprotty/sprotty#160]
The examples are much friendlier to the React ecosystem than Angular due to the use of JSX. Would it be possible to provide a simple example of a Sprotty diagram in Angular?

**Comment by spoenemann** [comment]
The examples do not use React, but [snabbdom-jsx](https://www.npmjs.com/package/snabbdom-jsx) to generate [Snabbdom](https://github.com/snabbdom/snabbdom) virtual DOMs using JSX. It's actually not so easy to use that syntax within a React project because it's not compatible with React's JSX.

We might consider switching to [snabbdom-pragma](https://github.com/Swizz/snabbdom-pragma), which is the "favorite way to use JSX with  Snabbdom", CC @JanKoehnlein.

**Comment by mscale-wmp** [comment]
I would like to revive this request. An angular example in the documentation would be very helpful since ng does not use JSX

**Comment by jonah-iden** [comment]
Hi, after thinking a bit about it i don't really think we need extra documentation for this. Integrating sprotty with angular is relatively simple. Just create a, Angular-component containing a div with an id like `"sprotty-container"`. In the [`ngAfterViewInit()`](https://angular.io/api/core/AfterViewInit#ngAfterViewInit) method you could then do the sprotty initialization and container creation passing in the container-id you specified previously (see [Sprotty Getting Started](https://sprotty.org/docs/getting_started/)). 
If you are talking about wanting to write sprotty views as Angular components, that is just not possible and would require a full rewrite of the sprotty rendering logic. So even if you integrate Sprotty into an Angular application you will still have to write sprotty-views in JSX.
