### ISSUE TITLE
Is LocalModelSource model recreation during user triggered move intended?

### ISSUE THREAD

**Issue by BjBe82** [eclipse-sprotty/sprotty#177]
We use a "global" index (SModelIndex) in our LocalModelSource which is used in some operations to speed them up. We now noticed a bug which occurred after the user moves a node in the browser.

After some investigation, we noticed that the Graph children are recreated (new instances). 

This means that the following code:
```
LocalModelSource:
...
  protected modelSourceIndex: SModelIndex<SModelElementSchema> = new SModelIndex<SModelElementSchema>();
...
 this.currentRoot.children.forEach(element => {
          var cachedElement = this.modelSourceIndex.getById(element.id);
          if (cachedElement !== element) {
            console.error('Not equal element: ' + element.id);
          }
        });
```
will report "Not equal elements" after the user has moved an element (other operations like calling the layout function will not create new instances of the children.)

I cross checked this with a MoveAction trigged programmatically but there the behavior is different:
```
     var elementToMove = { elementId: "id of the element", toPosition: { x: 100, y: 100 } };
     await this.actionDispatcher.dispatch(new MoveAction([elementToMove], true));
```
After the move the following is still true: `"(cachedElement === element)"`. This means the MoveAction itself does not recreate elements.

Is it intended that the child elements are recreated instead of updated?

If it is intended, we need to make sure to create a new index before each operation call which needs an index.

**Comment by spoenemann** [comment]
The reason is probably that the move feature also fires a CommitModelAction when the move is finished (mouseup event). That action replaces the external model held by the LocalModelSource with a reduced copy of the internal model held by the CommandStack.

I see three options, all overriding `commitModel` in your LocalModelSource subclass:
 * Make it a no-op. But then you miss updates triggered through the Sprotty UI, e.g. new element positions after a move.
 * Call `super.commitModel(newRoot)` and then recreate your index. You should check whether this causes a noticeable overhead.
 * Traverse all elements of your model and update properties according to the new model by keeping object identity (e.g. using a ModelMatcher). I don't think this would really improve performance compared to the previous solution, and it would require a much more complex solution.

**Comment by BjBe82** [comment]
Thanks for the response and clarification. For now we recreate the Index at the moment for each call to the functions which need the index and reuse it till the call chain ends.

I think the other solutions have a general downside in that case if we just recreate the index even if it is not needed. This might be more often the case dependent on what the user does in the UI.
