### ISSUE TITLE
Avoid/disable automatic changes of (macro) layout

### ISSUE THREAD

**Issue by m-morelli** [eclipse-sprotty/sprotty#306]
Hello, I've managed to prototype a VS Code extension with an Xtext-based language server and a Sprotty diagram for a simple DSL.

The next step is to avoid the layout changes that are automatically applied to the diagram, even for basic model modifications.

As an example, let's say that I have the Xtext model below and that I'm happy with the graphic arrangement of the corresponding nodes in the Sprotty diagram.

![1](https://user-images.githubusercontent.com/7499894/180414497-50fc3f9e-5d2f-4c6f-be08-5965aeeaf192.png)

Now, if I just enter a (empty) new line in the textual model, the layout is automatically adjusted and the graphic arrangement I was happy with is gone.

![2](https://user-images.githubusercontent.com/7499894/180414576-82e9c0de-f07a-420f-b7fd-058984173738.png)

[The doc](https://github.com/eclipse/sprotty/wiki/Client-Server-Protocol#layout-computation) says that "_the server is responsible for the macro layout, that is the arrangement of the main model elements (e.g. nodes and edges) with the goal of optimizing visual clarity and readability_". So, I've switched off the server layout (`needsServerLayout: false`), but I still get automatic changes, the only difference being that now all the blocks are moved to the same position, in the top left corner of the diagram (see below).

![3](https://user-images.githubusercontent.com/7499894/180414614-da50999c-e394-4b8a-83bb-49f54bd9c41a.png)

Any suggestions on how to completely disable this automatic arrangement of nodes and edges?

Thanks!

**Comment by spoenemann** [comment]
The scenario you are aiming for is very complex. When a text change is processed, a brand new instance of the diagram model is generated, erasing any manual changes the user has made in the frontend. In order to retain the manual positions, you'd need to send position information to the backend after every move, and store that information somewhere. This "somewhere" can be in the source model itself (e.g. annotations or comments to the respective blocks) or a separate file (e.g. `hello.btext.layout`) in a format of your choice (JSON, XML etc.)

**Comment by m-morelli** [comment]
Thanks for your answer. Any example to start with?

**Comment by spoenemann** [comment]
No, unfortunately I don't have a ready-to-use example for this scenario. To capture position changes, you could override `DiagramServerProxy.commitModel` so it sends the model to the backend with a custom action.
